sudo: required
dist: trusty
language: node_js
node_js:
  - "7.3"
cache:
  directories:
    - node_modules
install:
  - npm install -g gulp
  - npm install
script:
  # 代码检查&单元测试
  - gulp lint
  - gulp test